import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { ImageResponse } from "next/og";

import { BRAND_INK, BRAND_MUTED, BRAND_NAME, BRAND_SURFACE, MARK } from "@/lib/brand";
import { MARK_PATH } from "@/lib/brand-mark.generated";

export const alt = "Daniel Molloy | Independent Technology Advisory";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

/**
 * Satori has no system fonts, so the previous `fontFamily: "system-ui"` silently fell
 * back to Noto Sans and the card was never actually in the site's typeface.
 *
 * `new URL(..., import.meta.url)` is what makes the bundler trace the .ttf into the
 * deployment. It is read rather than fetched because fetch has no file: handler here
 * ("Error: not implemented... yet..."). Generated by `npm run brand`.
 */
function loadFont(relativePath: string) {
  return readFile(fileURLToPath(new URL(relativePath, import.meta.url)));
}

/** The mark, built from the same outlined path the favicon and nav use. */
const markDataUri = `data:image/svg+xml;base64,${Buffer.from(
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${MARK.size} ${MARK.size}">` +
    `<rect width="${MARK.size}" height="${MARK.size}" rx="${MARK.size * MARK.radiusRatio}" fill="${BRAND_INK}"/>` +
    `<path d="${MARK_PATH}" fill="${BRAND_SURFACE}"/>` +
    `</svg>`
).toString("base64")}`;

export default async function Image() {
  const [light, medium] = await Promise.all([
    loadFont("./fonts/Inter-Light.ttf"),
    loadFont("./fonts/Inter-Medium.ttf"),
  ]);

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: BRAND_SURFACE,
          fontFamily: "Inter",
          padding: 48,
        }}
      >
        <img
          src={markDataUri}
          width={88}
          height={88}
          alt=""
          style={{ marginBottom: 40 }}
        />
        <div style={{ fontSize: 56, fontWeight: 300, color: BRAND_INK, marginBottom: 16 }}>
          {BRAND_NAME}
        </div>
        <div style={{ fontSize: 36, fontWeight: 500, color: BRAND_INK, marginBottom: 24 }}>
          Independent Technology Advisory
        </div>
        <div
          style={{
            fontSize: 22,
            fontWeight: 300,
            color: BRAND_MUTED,
            textAlign: "center",
            maxWidth: 600,
          }}
        >
          Technical due diligence · Fractional CTO · AI governance
        </div>
      </div>
    ),
    {
      ...size,
      fonts: [
        { name: "Inter", data: light, weight: 300, style: "normal" },
        { name: "Inter", data: medium, weight: 500, style: "normal" },
      ],
    }
  );
}
